export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const GET_PROFILE = 'GET_PROFILE';
export const CHANGE_PROFILE = 'CHANGE_PROFILE';
export const CHANGE_PROFILE_SUCCESS = 'CHANGE_PROFILE_SUCCESS';
export const CHANGE_PROFILE_FAILED = 'CHANGE_PROFILE_FAILED';

export const LOGOUT = 'LOGOUT';

export const SEND_OTP = 'SEND_OTP';
export const SEND_OTP_FAILED = 'SEND_OTP_FAILED';
export const SEND_OTP_SUCCESS = 'SEND_OTP_SUCCESS';

export const VERIFY_OTP = 'VERIFY_OTP';
export const VERIFY_OTP_FAILED = 'VERIFY_OTP_FAILED';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';

export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';

export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const SET_NOTIFICATION_FAILED = 'SET_NOTIFICATION_FAILED'